name: Sitemap check example 2

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 6 * * *'

jobs:
  sitemap_check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locale: ['de-de', 'nl-nl', 'nl-en']
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Run Sitemap Check Action
          uses: Andy1Blue/sitemap-check@main
          with:
            sitemap_url: 'https://www.example.com/{locale}/sitemap.xml'
            exclude: 'microsoft.com,a.storyblok.com,_next,popages.com,youtube,facebook,instagram,object'
            slack_channel: '#prod_monitoring'
            slack_token: ${{ secrets.SLACK_TOKEN }}
          env:
            GITHUB_MATRIX_LOCALE: ${{ matrix.locale }}
