name: Sitemap check

on:
  workflow_dispatch:
    inputs:
      sitemap_url:
        description: 'The base URL of the sitemap, with a placeholder for locale'
        required: true
        default: 'https://www.example.com/{locale}/sitemap.xml'
      exclude:
        description: 'Comma separated list of domains to exclude'
        required: false
        default: 'microsoft.com,a.storyblok.com,_next,popages.com,youtube,facebook,instagram,object'
      slack_channel:
        description: 'The Slack channel to send results to.'
        required: true
        default: 'my-channel'
      slack_token:
        description: 'The Slack bot token to post messages.'
        required: true

  schedule:
    - cron: '0 6 * * *'

jobs:
  sitemap_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Sitemap Check Action
        uses: my-sitemap-check-action@v1
        with:
          sitemap_url: 'https://www.example.com/{locale}/sitemap.xml'
          exclude: 'example.com,anotherdomain.com'
          slack_channel: ${{ github.event.inputs.slack_channel }}
          slack_token: ${{ secrets.SLACK_TOKEN }}