name: Sitemap Check Example 1

on:
  workflow_dispatch:
    inputs:
      sitemap_url:
        description: 'The base URL of the sitemap, with a placeholder for locale'
        required: true
        default: 'https://www.example.com/{locale}/sitemap.xml'
      exclude:
        description: 'Comma separated list of domains to exclude'
        required: false
        default: 'microsoft.com,a.storyblok.com,_next,popages.com,youtube,facebook,instagram,object'
      slack_channel:
        description: 'The Slack channel to send results to.'
        required: true
        default: 'my-channel'
      slack_token:
        description: 'The Slack bot token to post messages.'
        required: true

  schedule:
    - cron: '0 6 * * *'

jobs:
  sitemap_check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locale: ['de-de', 'nl-nl', 'nl-en']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Sitemap Check Action
        uses: Andy1Blue/sitemap-check@v1
        with:
          sitemap_url: ${{ github.event.inputs.sitemap_url }}
          exclude: ${{ github.event.inputs.exclude }}
          slack_channel: ${{ github.event.inputs.slack_channel }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
        env:
          GITHUB_MATRIX_LOCALE: ${{ matrix.locale }}
